name: medical-records-besu

networks:
  besu-net:
    driver: bridge

volumes:
  hospital-a-data:
  hospital-b-data:
  hospital-c-data:

x-besu-base: &besu-base
  image: hyperledger/besu:24.12.2
  networks:
    - besu-net
  restart: unless-stopped

services:
  hospital-a:
    <<: *besu-base
    container_name: besu-hospital-a
    hostname: hospital-a
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./besu/genesis.json:/genesis/genesis.json:ro
      - ./besu/static-nodes.json:/genesis/static-nodes.json:ro
      - ./besu/nodes/hospital-a:/keys:ro
      - hospital-a-data:/data
    command:
      - --data-path=/data
      - --genesis-file=/genesis/genesis.json
      - --node-private-key-file=/keys/key
      - --static-nodes-file=/genesis/static-nodes.json
      - --network-id=1337
      - --min-gas-price=0
      - --p2p-host=0.0.0.0
      - --p2p-port=30303
      - --Xdns-enabled=true
      - --host-allowlist=*
      - --logging=INFO
      - --rpc-http-enabled
      - --rpc-http-host=0.0.0.0
      - --rpc-http-port=8545
      - --rpc-http-api=ETH,NET,WEB3,QBFT,IBFT,ADMIN
      - --rpc-http-cors-origins=*

  hospital-b:
    <<: *besu-base
    container_name: besu-hospital-b
    hostname: hospital-b
    ports:
      - "30304:30303"
    volumes:
      - ./besu/genesis.json:/genesis/genesis.json:ro
      - ./besu/static-nodes.json:/genesis/static-nodes.json:ro
      - ./besu/nodes/hospital-b:/keys:ro
      - hospital-b-data:/data
    command:
      - --data-path=/data
      - --genesis-file=/genesis/genesis.json
      - --node-private-key-file=/keys/key
      - --static-nodes-file=/genesis/static-nodes.json
      - --network-id=1337
      - --min-gas-price=0
      - --p2p-host=0.0.0.0
      - --p2p-port=30303
      - --Xdns-enabled=true
      - --host-allowlist=*
      - --logging=INFO

  hospital-c:
    <<: *besu-base
    container_name: besu-hospital-c
    hostname: hospital-c
    ports:
      - "30305:30303"
    volumes:
      - ./besu/genesis.json:/genesis/genesis.json:ro
      - ./besu/static-nodes.json:/genesis/static-nodes.json:ro
      - ./besu/nodes/hospital-c:/keys:ro
      - hospital-c-data:/data
    command:
      - --data-path=/data
      - --genesis-file=/genesis/genesis.json
      - --node-private-key-file=/keys/key
      - --static-nodes-file=/genesis/static-nodes.json
      - --network-id=1337
      - --min-gas-price=0
      - --p2p-host=0.0.0.0
      - --p2p-port=30303
      - --Xdns-enabled=true
      - --host-allowlist=*
      - --logging=INFO
